### ISSUE TITLE
关于uavs3e问题的请教

### ISSUE THREAD

**Issue by soaringleefighting** [Yang-Xijie/yang-xijie.github.io#8]

**Comment by soaringleefighting** [comment]
你好，看到你在uavs3e的github上提问了一些问题，可以请教一下你吗？
1、我在测试中发现uavs3e的编码速度非常慢，和x265/libaom不是在一个档次。
单线程配置，编码参数如下：
-speed_level 6 --input_bit_depth 8 --internal_bit_depth 8 --frm_threads 1 --wpp_threads 1 --rc_type 0 -p 100 -g 0 -v 2 --qp 27

**Comment by Yang-Xijie** [comment]
把`speed_level`调成4试一下？不然我也不太清楚
这段时间没有在做这个了，不好意思哈

**Comment by soaringleefighting** [comment]
好的，感谢~
